name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - name: Install mecab-ipadic
      run: sudo apt install mecab-ipadic-utf8
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.15.2'
        otp-version: '26.0'
    - run: mix deps.get
    - run: mix test
